### ISSUE TITLE
[PriorTeamNote]-ToDo: Multiple Reservations

### ISSUE THREAD

**Issue by SELord** [SELord/Schedule-it#2]
User can make multiple reservations for one event on the Make Reservation page.

**Comment by SaeHyoungOh** [comment]
This issue is only present in Chrome, and not in Firefox. It should be debugged after the homepage.php issue on Chrome is resolved first.

Edit: User can make multiple reservations for one SLOT on the Make Reservation page.
Making multiple reservations for one event is perfectly fine as long as it is permitted by the event creator..

**Comment by SaeHyoungOh** [comment]
On the "Make Reservation" or "Reservation Update" page, the list of available slots do not include the slots for which the invited user has already made a reservation. This will prevent the user from attempting to make duplicate reservations for a single slot.
In contrast to what I initially thought, the invited user is not able to reserve the same slot more than once; the web tool merely displays the "SUCCESS!!" page when the same slot is clicked again. This fix will prevent this issue altogether by not showing the already reserved slots at all.
See [commit](https://github.com/SELord/Schedule-it/commit/689914777d6ed763e2b74f12221dfd1fd7a893a7)
